---
jobs:
  - name: test-unit
    public: true
    plan:
      - get: bosh-agent
        trigger: true
      - task: test-unit
        file: bosh-agent/ci/tasks/test-unit.yml

  - name: test-integration
    public: false
    plan:
      - get: bosh-agent
        trigger: true
      - task: test-integration
        privileged: true
        file: bosh-agent/ci/tasks/test-integration.yml
        config:
          params:
            BOSH_AWS_ACCESS_KEY_ID: {{BOSH_AWS_ACCESS_KEY_ID}}
            BOSH_AWS_SECRET_ACCESS_KEY: {{BOSH_AWS_SECRET_ACCESS_KEY}}
            BOSH_LITE_KEYPAIR: {{BOSH_LITE_KEYPAIR}}
            BOSH_LITE_SUBNET_ID: {{BOSH_LITE_SUBNET_ID}}
            BOSH_LITE_NAME: {{BOSH_LITE_NAME}}
            BOSH_LITE_SECURITY_GROUP: {{BOSH_LITE_SECURITY_GROUP}}
            BOSH_LITE_PRIVATE_KEY: {{BOSH_LITE_PRIVATE_KEY}}

resources:
  - name: bosh-agent
    type: git
    source:
      uri: https://github.com/cloudfoundry/bosh-agent
      branch: 256.x-3233.x
